/** Types shared between the server API and the browser client. */

import type { FunscriptSuffixes } from './funscriptNames';
import type { InterpolationMethod } from './interpolation';
import type { VrFormat } from './vrFormat';

export type Album = 'album';
export type Single = 'single';
export type Audio = 'audio';
export type Video = 'video';
export type Playlist = 'playlist';

export type Stroker = 'stroker';
export type Buttplug = 'buttplug';
export type Vibrator = 'vibrator';
export type Estim = 'estim';
export type Machine = 'machine';
/** Funscript without a recognised type suffix; presented as "Generic". */
export type Unknown = 'unknown';

/** Identifies the role/channel of a Funscript file. */
export type FunscriptType = Stroker | Buttplug | Vibrator | Estim | Machine | Unknown;

/** Metadata for a single Funscript companion file. */
export interface FunscriptInfo {
  /** Opaque key the HAPPY Jellyfin plugin serves the file under. */
  key: string;
  /** File name including the extension, as found next to the media file. */
  filename: string;
  type: FunscriptType;
  /** Optional subcategory from `<stem>.<type>.<sub>.funscript`, e.g. `nipples`. */
  sub?: string;
}

/** Where a track's chapters were read from. */
export type ChapterSource = 'embedded' | 'funscript';

export const CHAPTER_SOURCES: readonly ChapterSource[] = ['embedded', 'funscript'];

/** A named time span of a media file, in seconds. */
export interface Chapter {
  name: string;
  start: number;
  end: number;
}

export interface LibraryItemBase {
  /** Jellyfin item id for tracks and playlists; derived from artist and album name for albums. */
  id: string;
  title: string;
  type: Audio | Video | Album;
}

/** All information the client needs to render a track card or open the player. */
export interface TrackInfo extends LibraryItemBase {
  /** 'video' for video files (e.g. mp4); the player and library UI treat them like tracks. */
  type: Audio | Video;
  /** File name of the media file, including extension; drives VR detection and the artist fallback. */
  filename: string;
  /** Markdown description (Jellyfin's overview, e.g. from the ID3 comment); empty when there is none. */
  description: string;
  artist: string;
  album: string;
  year: string;
  trackNumber: number | null;
  hasArtwork: boolean;
  /** Jellyfin image tag of the primary image; changes whenever the image does. */
  artworkTag: string | null;
  durationSeconds: number;
  funscripts: FunscriptInfo[];
  tags: string[];
  /** Sorted, non-overlapping chapters; absent when no configured source provides any. */
  chapters?: Chapter[];
  chaptersSource?: ChapterSource;
  /** Timeline thumbnails generated by Jellyfin; absent when trickplay has not run for this item. */
  trickplay?: TrickplayInfo;
}

/** One trickplay resolution of a Jellyfin item: tile sheets of `columns` × `rows` thumbnails. */
export interface TrickplayInfo {
  mediaSourceId: string;
  /** Resolution key in Jellyfin's tile URLs (the requested thumbnail width). */
  resolution: number;
  /** Actual thumbnail size in pixels within a sheet. */
  width: number;
  height: number;
  columns: number;
  rows: number;
  /** Total number of thumbnails across all sheets. */
  count: number;
  intervalSeconds: number;
}

export interface AlbumInfo extends LibraryItemBase {
  type: Album;
  album: string;
  artist: string;
  year: string;
  durationSeconds: number;
  trackIds: string[];
  trackCount: number;
  coverTrackId: string | null;
}

export interface PlaylistEntry {
  order: number;
  trackId: string;
  title: string;
  artist: string;
  album: string;
}

export interface PlaylistInfo {
  id: string;
  name: string;
  year: string;
  durationSeconds: number;
  entries: PlaylistEntry[];
}

/** A single action entry inside a Funscript file. */
export interface FunscriptAction {
  /** Timestamp in milliseconds. */
  at: number;
  /** Position value 0–100. */
  pos: number;
}

/** Parsed representation of a Funscript JSON file. */
export interface Funscript {
  version?: string;
  actions: FunscriptAction[];
}

/** The whole library as the client holds it in memory, built from Jellyfin's items. */
export interface LibraryResponse {
  tracks: TrackInfo[];
  videos: TrackInfo[];
  albums: AlbumInfo[];
  playlists: PlaylistInfo[];
}

/** Response shape of GET /api/version */
export interface VersionInfo {
  version: string;
  /** Release channel of the running build: `stable`, `preview`, or `dev`. */
  channel: string;
  commit: string | null;
  builtAt: string | null;
}

/** Response shape of GET /api/config: server-side defaults used when the client has no stored setting. */
export interface ClientSettings {
  videoSeekInterval: number;
  blurContent: boolean;
  hapticFrequency: number;
  hapticDelay: number;
  /** Absolute bound of the delay sliders, in milliseconds. */
  hapticDelayLimit: number;
  dglabEnabled: boolean;
  /** Only true when `dglabEnabled` is as well. */
  dglabSandboxEnabled: boolean;
  /** DG-Lab relay address as browsers and phones reach it; empty for the page's own origin. */
  dglabRelayUrl: string;
  autoReconnectIntiface: boolean;
  autoReconnectDglab: boolean;
  /** True when the server runs with `LOG_LEVEL=debug`. */
  debugLogging: boolean;
  funscriptInterpolationMethod: InterpolationMethod;
  funscriptColorGradient: boolean;
  cardViewForceSquareArtwork: boolean;
  cardViewLargePortraitArtwork: boolean;
  /** Jellyfin server address as reached from the browser; empty when not configured. */
  jellyfinUrl: string;
  funscriptSuffixes: FunscriptSuffixes;
  /** Chapter sources in order of precedence; the first source that provides chapters wins. */
  chapterSourcePriority: ChapterSource[];
}

export type QueueSource =
  | { type: Single }
  | { type: Album; id: string }
  | { type: Playlist; id: string };

/** Everything a player slot needs to render one track. */
export interface PlaybackRequest {
  /** Library id of the track, used to tell the two player slots apart. */
  id: string;
  type: Audio | Video;
  src: string;
  title: string;
  artist: string;
  year: string;
  poster: string;
  /** False when `poster` is only the placeholder art, which the player must not show. */
  hasArtwork: boolean;
  chapters: Chapter[];
  /** WebVTT chapters URL; null when the track has no chapters. */
  chaptersSrc: string | null;
  /** WebVTT storyboard URL; null for audio or when storyboards are disabled. */
  storyboardSrc: string | null;
  /** VR180 projection detected from the filename; absent for flat media. */
  vr?: VrFormat | null;
}